### ISSUE TITLE
More liberal licensing?

### ISSUE THREAD

**Issue by skyzyx** [briancray/PHP-URL-Shortener#2]
I'm interested in using the id-to-code and code-to-id functions from this project, but since the GPL is a viral license I can't currently use it without changing the licensing from my project from the more liberal Apache 2.0 to the more restrictive GPL v2.

Is there any chance you'd be willing to grant me the ability to use these functions under the Apache 2.0, New BSD or MIT licenses?

Thanks!

**Comment by briancray** [comment]
What's the nature of your product?

**Comment by skyzyx** [comment]
I'm working on an open-source video sharing site. It's something that people can take, tweak and deploy. I'm interested in the algorithm for generating the shorter URLs, without the rest of the rest of the code.

Out of curiosity, why GPL v2?

**Comment by briancray** [comment]
Because that was recommended. 

Anyway, yes you can use the portions in question for your project. Hope it helps!

Cheers
Brian

**Comment by skyzyx** [comment]
That's awesome; thank you! :) But I need to dot my Is and cross my Ts. Is there any way you would be willing to explicitly state that you grant Amazon Web Services the right to use this code under the Apache 2.0 license?

The reason I ask is this: the team I work on at AWS is an open-source team, who provides SDKs and tools to customers under the Apache 2.0 license. The reason we can't touch the GPL is because it's a **viral** license. That means that if you include even a single line of GPL code in your project, your entire project becomes forcibly GPL'd as well. There is language in there about patent rights that no intelligent corporation would ever touch. The GPL is as restrictive as any closed-source license, in that it **forces** you to make your code available.

The MIT/BSD/Apache 2.0 licenses are casually referred to as "do whatever you want" licenses. This enables people (or other corporations) to integrate open-source code into anything they want: internal-only projects, closed-source projects, or open-source projects. They don't forcibly change the license of the project they're integrated into, which makes them more "free" (in terms of restrictions).

AWS licenses all of its open-source code as Apache 2.0, which allows the users of that code to use it in whatever way works for them — corporations, individuals, partnerships or otherwise. There's less lawyer-wrangling and more Getting Stuff Done™. :)

For this project, we're teaching people how to leverage the cloud to build real-world applications by building a real-world app and giving the source code away. People may choose to launch with a provider _other_ than AWS, and that's fine. I want to call that out specifically in case you had concerns about AWS using your code to lock users into our own platform. We're not. :)

Anyway, thank you for your time and willingness to cooperate on this. :)

Cheers!
-- Ryan

**Comment by briancray** [comment]
I grant Amazon Web Services the right to use the PHP URL shortener code under the Apache 2.0 license

**Comment by skyzyx** [comment]
Awesome, thank you! :)
