### ISSUE TITLE
Check URL failing

### ISSUE THREAD

**Issue by daverogers** [briancray/PHP-URL-Shortener#7]
CHECK_URL set to true, but an entry like "http://www.blahkj0392309i.com/ldjf09" is not rejected. Fresh install with no other files on the domain, running through your basic form on index.

**Comment by briancray** [comment]
hrmm, I'll check it out

**Comment by briancray** [comment]
Just to check -- do you have cURL enabled on your host?

**Comment by daverogers** [comment]
Apologies for not getting back to you quickly. Yes cURL is enabled on my host (libcurl/7.23.1).

**Comment by yiannisc** [comment]
I have the same issue. If you go to http://yan.is/zzzzzz you get a blank page. Any ideas?

I have: libcurl/7.15.5

Many Thanks,
Yiannis

**Comment by aimeelaplant** [comment]
I believe I'm having the same problem too. When I first installed the script, it made about 60 urls and wouldn't make anymore. I deleted everything, re-installed it, and it made about 8 URLs, so I'm not sure what's up, and it's not throwing any errors. I do have cURL enabled too.
